
export const ADD_TO_FAVORITES ='ADD_TO_FAVORITES'
export const ADD_TO_FAVORITES_IS_LOADIING ='ADD_TO_FAVORITES_IS_LOADING'
export const ADD_TO_FAVORITES_SUCCESS ='ADD_TO_FAVORITES_SUCCESS'
export const ADD_TO_FAVORITES_HAS_ERROR ='ADD_TO_FAVORITES_HAS_ERROR'

