
export const GET_FAVORITES ='GET_FAVORITES'
export const GET_FAVORITES_IS_LOADIING ='GET_FAVORITES_IS_LOADING'
export const GET_FAVORITES_SUCCESS ='GET_FAVORITES_SUCCESS'
export const GET_FAVORITES_HAS_ERROR ='GET_FAVORITES_HAS_ERROR'

