
export const SEARCH_MOVIE ='SEARCH_MOVIE'
export const SEARCH_MOVIE_IS_LOADIING ='SEARCH_MOVIE_IS_LOADING'
export const SEARCH_MOVIE_SUCCESS ='SEARCH_MOVIE_SUCCESS'
export const SEARCH_MOVIE_HAS_ERROR ='SEARCH_MOVIE_HAS_ERROR'

