export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const IS_LOGGED = 'IS_LOGGED';

export const LOGIN_HAS_ERROR = 'LOGIN_HAS_ERROR';

export const LOGIN_IS_LOADING = 'LOGIN_IS_LOADING';



export const REGITER_USER_SUCCESS = 'REGITER_USER_SUCCESS'
export const REGISTER_HAS_ERROR = 'REGISTER_HAS_ERROR';
export const REGISTER_IS_LOADING = 'REGISTER_IS_LOADING';
export const REGISTER = 'REGISTER';
export const IS_REGISTERED = 'IS_REGISTERED';
export const CALLBACK_MSG='CALLBACK_MSG';

export const DASHBOARD_IS_LOADING = 'DASHBOARD_IS_LOADING'
export const DASHBOARD_HAS_ERROR = 'DASHBOARD_HAS_ERROR'
export const GET_DASHBOARD_HAS_ERROR ='GET_DASHBOARD_HAS_ERROR'
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS'
export const GET_DASHBOARD = 'GET_DASHBOARD'

export const ACCIDENT_IS_LOADING = 'ACCIDENT_IS_LOADING'
export const ACCIDENT_HAS_ERROR = 'ACCIDENT_HAS_ERROR'
export const POST_ACCIDENT_SUCCESS = 'POST_ACCIDENT_SUCCESS'
export const POST_ACCIDENT = 'POST_ACCIDENT'

export const HEALTHREPORT_IS_LOADING = 'HEALTHREPORT_IS_LOADING'
export const HEALTHREPORT_HAS_ERROR = 'HEALTHREPORT_HAS_ERROR'
export const GET_HEALTHREPORT_SUCCESS = 'GET_HEALTHREPORT_SUCCESS'
export const GET_HEALTHREPORT = 'GET_HEALTHREPORT'

export const TRIPSLIST_NORMAL_IS_LOADING = 'TRIPSLIST_NORMAL_IS_LOADING'
export const TRIPSLIST_NORMAL_HAS_ERROR = 'TRIPSLIST_NORMAL_HAS_ERROR'
export const GET_TRIPSLIST_NORMAL_SUCCESS = 'GET_TRIPSLIST_NORMAL_SUCCESS'
export const GET_TRIPSLIST_NORMAL = 'GET_TRIPSLIST_NORMAL'

export const TRIPSLIST_WARNING_IS_LOADING = 'TRIPSLIST_WARNING_IS_LOADING'
export const TRIPSLIST_WARNING_HAS_ERROR = 'TRIPSLIST_HAS_ERROR'
export const GET_TRIPSLIST_WARNING_SUCCESS = 'GET_TRIPSLIST_SUCCESS'
export const GET_TRIPSLIST_WARNING = 'GET_TRIPSLIST_WARNING'

export const TRIPSDETAILS_IS_LOADING = 'TRIPSDETAILS_IS_LOADING'
export const TRIPSDETAILS_HAS_ERROR = 'TRIPSDETAILS_HAS_ERROR'
export const GET_TRIPSDETAILS_SUCCESS = 'GET_TRIPSDETAILS_SUCCESS'
export const GET_TRIPSDETAILS = 'GET_TRIPSDETAILS'

export const GET_PROFILE_IS_LOADING = 'GET_PROFILE_IS_LOADING'
export const GET_PROFILE_HAS_ERROR = 'GET_PROFILE_HAS_ERROR'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE = 'GET_PROFILE'

export const UPDATE_PROFILE_IS_LOADING = 'UPDATE_PROFILE_IS_LOADING'
export const UPDATE_PROFILE_HAS_ERROR = 'UPDATE_PROFILE_HAS_ERROR'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const IS_UPDATED = 'IS_UPDATED';

export const UPLOAD_PIC_IS_LOADING = 'UPLOAD_PIC_IS_LOADING'
export const UPLOAD_PIC_HAS_ERROR = 'UPLOAD_PIC_HAS_ERROR'
export const UPLOAD_PIC_SUCCESS = 'UPLOAD_PIC_SUCCESS'
export const UPLOAD_PIC= 'UPLOAD_PIC'
export const IS_UPLOADED = 'IS_UPLOADED';

export const GET_LOCATION = 'GET_LOCATION';
export const LOCATION_PERMISSION_BEGIN = 'LOCATION_PERMISSION_BEGIN';
export const LOCATION_PERMISSION_SET = 'LOCATION_PERMISSION_SET';
export const LOCATION_SET = 'LOCATION_SET';

export const CREATE_VEHICLE_IS_LOADING = 'CREATE_VEHICLE_IS_LOADING';
export const IS_CREATED = 'IS_CREATED';
export const CREATE_VEHICLE_HAS_ERROR = 'CREATE_VEHICLE_HAS_ERROR';
export const CREATE_VEHICLE_SUCCESS = 'CREATE_VEHICLE_SUCCESS'

export const GET_VEHICLE_MODELS_IS_LOADING = 'GET_VEHICLE_MODELS_IS_LOADING';
export const GET_VEHICLE_MODELS_HAS_ERROR = 'GET_VEHICLE_MODELS_HAS_ERROR';
export const GET_VEHICLE_MODELS_SUCCESS = 'GET_VEHICLE_MODELS_SUCCESS'
export const VEHICLE_CALLBACK_MSG='VEHICLE_CALLBACK_MSG';

export const GET_VEHICLES_IS_LOADING = 'GET_VEHICLES_IS_LOADING';
export const GET_VEHICLES_HAS_ERROR = 'GET_VEHICLES_HAS_ERROR';
export const GET_VEHICLES_SUCCESS = 'GET_VEHICLES_SUCCESS'
export const GET_VEHICLES_CALLBACK_MSG='GET_VEHICLES_CALLBACK_MSG';

export const GET_NOTIFICATIONS_IS_LOADING = 'GET_NOTIFICATIONS_IS_LOADING';
export const GET_NOTIFICATIONS_HAS_ERROR = 'GET_NOTIFICATIONS_HAS_ERROR';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS'
export const GET_NOTIFICATIONS_CALLBACK_MSG='GET_NOTIFICATIONS_CALLBACK_MSG';
export const GET_NOTIFICATIONS_LIST = 'GET_NOTIFICATIONS_LIST'

export const NAVIGATION_SELECTED = 'NAVIGATION_SELECTED'

export const MAIN_SELECTED = 'MAIN_SELECTED' 
export const REPORT_SELECTED = 'REPORT_SELECTED'
export const TRIPS_SELECTED = 'TRIPS_SELECTED'
export const SETTINGS_SELECTED = 'SETTINGS_SELECTED'
export const NOTIFICATIONS_SELECTED = 'NOTIFICATIONS_SELECTED'

export const SEARCH_MOVIE ='SEARCH_MOVIE'
export const SEARCH_MOVIE_IS_LOADIING ='SEARCH_MOVIE_IS_LOADING'
export const SEARCH_MOVIE_SUCCESS ='SEARCH_MOVIE_SUCCESS'
export const SEARCH_MOVIE_HAS_ERROR ='SEARCH_MOVIE_HAS_ERROR'

