# plugin 'cocoapods-fix-react-native'

platform :ios, '9.0'

use_frameworks!

target 'imdbNohaElsheweikh' do
    pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
    pod 'React', path: '../node_modules/react-native/', :subspecs => [
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTLinkingIOS',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'DevSupport',
    'CxxBridge',
    ]
    
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
    pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
    pod 'SwiftyJSON', '4.0.0'      
    pod 'Charts', '3.2.2'  
    pod 'react-native-fetch-blob',:path => '../node_modules/react-native-fetch-blob'
    pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
    # pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'instabug-reactnative', :path => '../node_modules/instabug-reactnative'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'



  pod 'RNShare', :path => '../node_modules/react-native-share'

end

swift4 = ['Charts']

post_install do |installer|
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if swift4.include?(target.name)
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
